# security.yaml
# Enterprise-grade security configuration for Go-Spec-Mock

# API Key Authentication Configuration
auth:
  enabled: true
  header_name: "X-API-Key"      # Header name for API keys (default: X-API-Key)
  query_param_name: "api_key"   # Query parameter name for API keys (default: api_key)
  keys:
    - key: "YOUR_GENERATED_API_KEY"
      name: "my-app"
      enabled: true
      expires_at: "2024-12-31T23:59:59Z"  # Optional expiration (RFC3339 format)
      rate_limit:                        # Optional per-key rate limiting
        requests_per_second: 50
        burst_size: 100
        window_size: "1m"
      metadata:                          # Optional key metadata for organization
        department: "engineering"
        environment: "development"
        owner: "team-alpha"
        description: "Development key for API testing"

# Cross-Origin Resource Sharing (CORS) Configuration
cors:
  enabled: true
  allowed_origins:                  # List of allowed origins (use specific origins instead of wildcard for security)
    - "http://localhost:3000"
    - "https://yourdomain.com"
    - "https://app.yourdomain.com"
  allowed_methods:                  # HTTP methods to allow
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "PATCH"
  allowed_headers:                  # Headers to allow
    - "Content-Type"
    - "Authorization"
    - "Accept"
    - "X-Requested-With"
    - "X-API-Key"
  allow_credentials: false          # Whether to allow credentials (cookies, authorization headers)
  max_age: 86400                    # Preflight cache duration in seconds (24 hours)

# Security Headers Configuration
security:
  # Content Security Policy (CSP) - prevents XSS attacks
  content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'"
  
  # HTTP Strict Transport Security (HSTS) - forces HTTPS
  strict_transport_security: "max-age=31536000; includeSubDomains"
  
  # Security headers
  x_content_type_options: "nosniff"     # Prevents MIME type sniffing
  x_frame_options: "DENY"               # Prevents clickjacking
  x_xss_protection: "1; mode=block"     # Basic XSS protection
  
  # Host validation - restrict which hosts can serve the API
  allowed_hosts:
    - "localhost"
    - "yourdomain.com"
    - "api.yourdomain.com"

# Global Rate Limiting Configuration
rate_limit:
  enabled: true
  strategy: "both"                    # Options: "ip", "api_key", "both"
  global:
    requests_per_second: 100
    burst_size: 200
    window_size: "1m"
  
  # Memory management for rate limiter
  cleanup_interval: "1m"              # How often to clean expired entries
  max_cache_size: 10000               # Maximum number of rate limit entries to keep in memory
  
  # IP-based rate limiting specific settings
  ip:
    requests_per_second: 50
    burst_size: 100
    window_size: "1m"
  
  # API key-based rate limiting specific settings
  api_key:
    requests_per_second: 200
    burst_size: 400
    window_size: "1m"

# Additional Security Settings
logging:
  mask_sensitive_data: true           # Mask API keys and sensitive data in logs
  
request_limits:
  max_request_size: 10485760          # 10MB default, configurable via CLI
  max_header_size: 102400             # 100KB max header size