# Go-Spec-Mock Configuration File
# This file demonstrates all available configuration options

# Server Configuration
server:
  host: "localhost"
  port: "8080"

# Security Configuration
security:
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
    allowed_headers: ["Content-Type", "Authorization", "Accept", "X-Requested-With"]
    allow_credentials: false
    max_age: 86400

# Observability Configuration
observability:
  logging:
    level: "info"  # "debug", "info", "warn", "error"
    format: "json"  # "json" or "console"

# Hot Reload Configuration
hot_reload:
  enabled: true
  debounce: "500ms"

# Proxy Configuration
# Forwards requests for undefined endpoints to a target server
proxy:
  enabled: false
  target: "https://api.example.com"
  timeout: "30s"

# OpenAPI Specification
spec_file: "./examples/petstore.yaml"

# TLS Configuration
# Enables HTTPS for the mock server.
# To generate a self-signed certificate for local testing:
# openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes
tls:
  enabled: false
  cert_file: "cert.pem"  # Path to your TLS certificate file
  key_file: "key.pem"     # Path to your TLS private key file