# Go-Spec-Mock Configuration File
# This file demonstrates all available configuration options

# Server Configuration
server:
  host: "localhost"
  port: "8080"
  metrics_port: "9090"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"
  max_request_size: 10485760  # 10MB
  shutdown_timeout: "30s"

# Security Configuration
security:
  auth:
    enabled: false
    header_name: "X-API-Key"
    query_param_name: ""  # Alternative to header
    keys:
      - key: "your-secure-api-key-here"
        name: "admin"
        enabled: true
        created_at: "2024-01-01T00:00:00Z"
      - key: "another-key-here"
        name: "readonly"
        enabled: true
        created_at: "2024-01-01T00:00:00Z"
  rate_limit:
    enabled: false
    strategy: "ip"  # "ip", "api_key"
    global:
      requests_per_second: 100
      burst_size: 200
      window_size: "1m"
    by_ip:
      requests_per_second: 60
      burst_size: 120
      window_size: "1m"
    by_api_key:
      api-key-1:
        requests_per_second: 10
        burst_size: 20
        window_size: "1m"
  headers:
    enabled: true
    content_security_policy: "default-src 'self'"
    hsts_max_age: 31536000
    allowed_hosts: []
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
    allowed_headers: ["Content-Type", "Authorization", "Accept", "X-Requested-With"]
    allow_credentials: false
    max_age: 86400

# Observability Configuration
observability:
  logging:
    level: "info"  # "debug", "info", "warn", "error"
    format: "json"  # "json" or "console"
  metrics:
    enabled: true
    path: "/metrics"
  tracing:
    enabled: false

# Hot Reload Configuration
hot_reload:
  enabled: true
  debounce: "500ms"

# Proxy Configuration
# Forwards requests for undefined endpoints to a target server
proxy:
  enabled: false
  target: "https://api.example.com"
  timeout: "30s"

# OpenAPI Specification
spec_file: "./examples/petstore.yaml"

# TLS Configuration
# Enables HTTPS for the mock server.
# To generate a self-signed certificate for local testing:
# openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes
tls:
  enabled: false
  cert_file: "cert.pem"  # Path to your TLS certificate file
  key_file: "key.pem"     # Path to your TLS private key file