# Go-Spec-Mock configuration demonstrating the major options available.
# Values shown here mirror the defaults unless otherwise noted.

server:
  host: "localhost"
  port: "8080"

security:
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
    allowed_headers: ["Content-Type", "Authorization", "Accept", "X-Requested-With"]
    allow_credentials: false
    max_age: 86400

observability:
  logging:
    level: "info"        # "debug", "info", "warn", "error"
    format: "json"        # "json" or "console"
    output: "stdout"      # "stdout", "stderr", or a file path
    development: false    # Enables zap development mode when true

hot_reload:
  enabled: true
  debounce: "500ms"

proxy:
  enabled: false
  target: "https://api.example.com"  # Required if proxy.enabled is true
  timeout: "30s"                     # Defaults to 30s when omitted

spec_file: "./examples/petstore.yaml"

tls:
  enabled: false
  cert_file: "cert.pem"  # Required when TLS is enabled
  key_file: "key.pem"
