# Minimal configuration for Go-Spec-Mock.
# The only required setting is the OpenAPI specification file.

spec_file: "./examples/petstore.yaml"

# Host defaults to "localhost" and port defaults to "8080".
# Override them with CLI flags or environment variables when needed.
