# Security-focused configuration for Go-Spec-Mock.
# Tightens CORS, disables hot reload, and prepares for TLS hardening.

server:
  host: "localhost"
  port: "8080"

security:
  cors:
    enabled: true
    allowed_origins: ["https://localhost:3000", "https://127.0.0.1:3000"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization", "Accept", "X-Requested-With", "X-API-Key"]
    allow_credentials: true
    max_age: 3600

observability:
  logging:
    level: "warn"
    format: "json"
    output: "stdout"
    development: false

spec_file: "./examples/petstore.yaml"

proxy:
  enabled: false          # Enable only when you trust the upstream target
  target: ""
  timeout: "30s"

hot_reload:
  enabled: false          # Disable file watching for production-like environments
  debounce: "500ms"

tls:
  enabled: false
  cert_file: "certs/server.crt"  # Provide real paths before enabling TLS
  key_file: "certs/server.key"
