# Security-focused configuration for Go-Spec-Mock
# This configuration prioritizes security and monitoring

server:
  host: "localhost"
  port: "8080"

# Comprehensive security configuration
security:
  cors:
    enabled: true
    allowed_origins: ["https://localhost:3000", "https://127.0.0.1:3000"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization", "Accept", "X-Requested-With", "X-API-Key"]
    allow_credentials: true
    max_age: 3600

# Enhanced observability
observability:
  logging:
    level: "debug"
    format: "json"

spec_file: "./examples/petstore.yaml"

# Proxy is disabled for security reasons
proxy:
  enabled: false
  target: ""
  timeout: "30s"

# Hot reload is disabled for production-like environments
hot_reload:
  enabled: false
  debounce: "500ms"